# Site settings
title: Teaching Politics

# email:

description: > # this means to ignore newlines until "baseurl:"
  Teaching political science: notes, resources, etc.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: TeachPolitics
github_username:  teaching-politics

# Build settings
# markdown: kramdown
# highlighter: rouge
