# Dependencies
#markdown:            redcarpet
#highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Teaching Politics
tagline:             'Teaching political science to undergraduates'
description:         'A place to share resources for teaching political science'
url:                 http://teaching-politics.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Michael Broschinsky
  url:               https://twitter.com/TeachPolitics
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
